In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("cardio.csv")

In [3]:
df

,Patient_ID,Age,Sex,Heart_Rate_bpm,Systolic_BP_mmHg,Diastolic_BP_mmHg,SpO2_percent,Temperature_C,Glucose_mg_dL,Cholesterol_mg_dL,...,Hypertension,Chest_Pain,PR_Interval_ms,QRS_Duration_ms,QT_Interval_ms,ST_Deviation_mV,RR_Interval_Std_ms,Admission_Date,ECG_Result,Risk_Severity
0,P10753,36.0,Female,59.0,127.0,76.0,95.0,36.5,NaN,218.9,...,Yes,Mild,195.0,115.0,379.0,-0.28,25.16,2025-10-07,Normal,Normal
1,P10520,64.0,Female,120.0,149.0,60.0,99.1,37.3,55.0,238.5,...,No,Moderate,194.0,77.0,421.0,-1.55,64.00,2025-12-05,Normal,Normal
2,P10211,61.0,Female,76.0,133.0,54.0,98.5,37.4,130.2,218.7,...,No,Mild,150.0,102.0,386.0,-0.50,53.86,2024-12-06,Normal,Normal
3,P10612,51.0,Male,62.0,NaN,67.0,98.5,36.2,109.3,212.1,...,No,NaN,179.0,77.0,351.0,0.84,59.91,2025-12-21,Normal,Normal
4,P10915,50.0,Female,81.0,149.0,67.0,97.2,37.4,134.8,271.9,...,No,NaN,198.0,93.0,407.0,-1.93,45.63,2024-12-08,Normal,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1010,P10107,82.0,Male,70.0,143.0,69.0,96.2,36.1,74.1,154.8,...,Yes,Moderate,164.0,114.0,424.0,-0.60,41.68,2024-12-20,Normal,Normal
1011,P10271,75.0,Female,69.0,117.0,97.0,98.5,36.8,97.3,208.3,...,No,Mild,194.0,NaN,421.0,-0.19,62.90,2026-04-10,Normal,Normal
1012,P10861,55.0,Male,71.0,133.0,62.0,96.1,37.1,62.1,NaN,...,Yes,NaN,101.0,98.0,355.0,-0.65,47.14,2026-04-27,Normal,Normal
1013,P10436,53.0,Female,67.0,143.0,89.0,97.2,36.8,55.5,245.6,...,No,Mild,129.0,98.0,407.0,-0.52,59.12,2024-10-25,Normal,Normal
1014,P10103,47.0,Female,69.0,120.0,81.0,97.6,35.7,87.9,229.6,...,No,NaN,145.0,107.0,397.0,1.51,36.20,2025-04-07,Normal,Normal

In [ ]:
#EDA
df.head()

,Patient_ID,Age,Sex,Heart_Rate_bpm,Systolic_BP_mmHg,Diastolic_BP_mmHg,SpO2_percent,Temperature_C,Glucose_mg_dL,Cholesterol_mg_dL,...,Hypertension,Chest_Pain,PR_Interval_ms,QRS_Duration_ms,QT_Interval_ms,ST_Deviation_mV,RR_Interval_Std_ms,Admission_Date,ECG_Result,Risk_Severity
0,P10753,36.0,Female,59.0,127.0,76.0,95.0,36.5,NaN,218.9,...,Yes,Mild,195.0,115.0,379.0,-0.28,25.16,2025-10-07,Normal,Normal
1,P10520,64.0,Female,120.0,149.0,60.0,99.1,37.3,55.0,238.5,...,No,Moderate,194.0,77.0,421.0,-1.55,64.00,2025-12-05,Normal,Normal
2,P10211,61.0,Female,76.0,133.0,54.0,98.5,37.4,130.2,218.7,...,No,Mild,150.0,102.0,386.0,-0.50,53.86,2024-12-06,Normal,Normal
3,P10612,51.0,Male,62.0,NaN,67.0,98.5,36.2,109.3,212.1,...,No,NaN,179.0,77.0,351.0,0.84,59.91,2025-12-21,Normal,Normal
4,P10915,50.0,Female,81.0,149.0,67.0,97.2,37.4,134.8,271.9,...,No,NaN,198.0,93.0,407.0,-1.93,45.63,2024-12-08,Normal,Normal

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1015 entries, 0 to 1014
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Patient_ID          1015 non-null   str
 1   Age                 995 non-null    float64
 2   Sex                 1015 non-null   str
 3   Heart_Rate_bpm      985 non-null    float64
 4   Systolic_BP_mmHg    989 non-null    float64
 5   Diastolic_BP_mmHg   1015 non-null   float64
 6   SpO2_percent        995 non-null    float64
 7   Temperature_C       1015 non-null   float64
 8   Glucose_mg_dL       974 non-null    float64
 9   Cholesterol_mg_dL   980 non-null    float64
 10  Hemoglobin_g_dL     984 non-null    float64
 11  Smoking_Status      995 non-null    str
 12  Diabetes            1015 non-null   str
 13  Hypertension        1015 non-null   str
 14  Chest_Pain          478 non-null    str
 15  PR_Interval_ms      1015 non-null   float64
 16  QRS_Duration_ms     990 non-null    float64
 17  QT_Interval_ms      1015 non-null   float64
 18  ST_Deviation_mV     985 non-null    float64
 19  RR_Interval_Std_ms  1015 non-null   float64
 20  Admission_Date      1015 non-null   str
 21  ECG_Result          1015 non-null   str
 22  Risk_Severity       1015 non-null   str
dtypes: float64(14), str(9)
memory usage: 182.5 KB